services:
    mock-nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./nginx/dev.conf.d/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/dev.conf.d/site.conf:/etc/nginx/conf.d/site.conf
        environment:
            TZ: Europe/Moscow
        networks:
            - app-network
        depends_on:
            - mock-backend
            - mock-frontend

    mock-db:
        container_name: mock-db
        image: postgres:17-alpine
        restart: unless-stopped
        environment:
            POSTGRES_USER: mock-server
            POSTGRES_PASSWORD: mock-server
            POSTGRES_DB: mock-server
            TZ: Europe/Moscow
        ports:
            - "127.0.0.1:5432:5432"
        volumes:
            - db_data:/var/lib/postgresql/data
        networks:
            - app-network

    mock-frontend:
        container_name: mock-frontend
        working_dir: /var/app
        restart: unless-stopped
        build:
            context: ./frontend
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        networks:
            - app-network
        volumes:
            - ./frontend:/var/app
            - /var/app/node_modules

    mock-backend:
        container_name: mock-backend
        working_dir: /var/app
        restart: unless-stopped
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - '4200:4200'
        networks:
            - app-network
        volumes:
            - ./backend:/var/app
            - /var/app/node_modules
        depends_on:
            - mock-db

volumes:
    db_data:

networks:
    app-network:
        driver: bridge