services:
    mock-nginx:
        ports:
            - "80:80"
        volumes:
            - ./nginx/dev.conf.d/nginx.conf:/etc/nginx/nginx.conf
            - ./nginx/dev.conf.d/site.conf:/etc/nginx/conf.d/site.conf

    mock-frontend:
        build:
            dockerfile: prod.Dockerfile


    mock-backend:
        build:
            dockerfile: prod.Dockerfile
